### ISSUE TITLE
【功能建议】 表格的表头是否可以添加固定，当页面滚动后，看不到每一列表示什么意思。

### ISSUE THREAD

**Issue by sunkangchina** [jqhph/dcat-admin#1276]

**Comment by ufucms** [comment]
用css样式可以解决了。
在resources/css中 新建样式文件 _table.css，然后在app.css中导入  `@import "_table.css";`

然后laravel-mix编译资源，就可以了。

_table.css 样式文件
```css
.table-main{
  table-layout: fixed;
  width: 100%;
}

.table-main table.custom-data-table td,
.table-main table.custom-data-table th{
  z-index: 0;
}

.table-main table.custom-data-table thead,
.table-fixed table.custom-data-table thead tr th{
    position: sticky;
    top: 0;
    background-color: #ececf1;
}
.table-fixed table.custom-data-table thead tr th {
  z-index: 99;
}
```
------------
下面这段可以根据自己情况，我加的原因是其他的样式把表格里面的 img和svg display: block了

```css
.table-main img,
.table-main svg{
  display: inline-block;
}
```
