### ISSUE TITLE
建议给数据表格加上固定表头功能

### ISSUE THREAD

**Issue by acshiryu** [jqhph/dcat-admin#492]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
当行和列都比较多时，不固定表头都不知道那一列是什么数据

**Comment by jqhph** [comment]
后面有空会加上这个功能

**Comment by ufucms** [comment]
我也在找可以固定表头的方法，最后用css样式解决了。
我是在resources/css中 新建样式文件 _table.css，然后在app.css中导入  `@import "_table.css";`

然后laravel-mix编译资源，就可以解决了。

_table.css 样式文件
```css
.table-main{
  table-layout: fixed;
  width: 100%;
}

.table-main table.custom-data-table td,
.table-main table.custom-data-table th{
  z-index: 0;
}

.table-main table.custom-data-table thead,
.table-fixed table.custom-data-table thead tr th{
    position: sticky;
    top: 0;
    background-color: #ececf1;
}
.table-fixed table.custom-data-table thead tr th {
  z-index: 99;
}
```
------------
下面这段可以根据自己情况，我加的原因是其他的样式把表格里面的 img和svg display: block了

```css
.table-main img,
.table-main svg{
  display: inline-block;
}
```
